import pandas as pd
df = pd.read_csv('my.csv')
df = df.dropna()
dfObj = df.sort_values(by=['tcp.stream', 'frame.time'])
dfObj.columns = dfObj.columns.str.replace('frame.time','ftime')
dfObj['ftime'] = dfObj['ftime'].map(lambda x: str(x)[:-3])
dfObj['ftime'] = dfObj['ftime'].map(lambda x: str(x)[12:])
dfObj['ftime'] = dfObj['ftime'].str.strip()
dfObj['ftime'] = pd.to_datetime(dfObj['ftime'], format="%H:%M:%S.%f")
timed = pd.DataFrame()
timed['new_value'] = dfObj.groupby('tcp.stream')['ftime'].shift()
print(timed)
dfObj['diff'] = dfObj.ftime - timed.new_value
newdf = pd.DataFrame()
newdf['duration'] = dfObj.groupby('tcp.stream')['ftime'].max() - dfObj.groupby('tcp.stream')['ftime'].min()
newdf['tcp len min'] = dfObj.groupby('tcp.stream')['tcp.len'].min() 
newdf['tcp len max'] = dfObj.groupby('tcp.stream')['tcp.len'].max() 
newdf['tcp len mean'] = dfObj.groupby('tcp.stream')['tcp.len'].mean() 
newdf['tcp len std'] = dfObj.groupby('tcp.stream')['tcp.len'].std() 
newdf['IAT min'] = dfObj.groupby('tcp.stream')['diff'].min() 
newdf['IAT max'] = dfObj.groupby('tcp.stream')['diff'].max()
#newdf['IAT mean'] = dfObj.groupby('tcp.stream')['diff'].mean()
newdf['IAT std'] = dfObj.groupby('tcp.stream')['diff'].std()
print(newdf)

